<!DOCTYPE html>
<html lang="fr">
    <!-- debut de la balise head-->
<head>
 <!--debut de la balise meta --> 
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
<!--Fin de la balise meta-->

<!--Titre et CSS-->
    <title>Jarditou</title>
    <link rel="stylesheet" href="./jarditou_css/assets/css/styles.css">
    <!-- Bootstrap-->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
</head>
<!--Fin de la balise head-->

<!--debut de la balise body -->
<body>
<header>
        <img id="logoj" src="./src/img/jarditou_logo.png" alt="jarditou logo">
        <article>
         <p class="text-center"><a href="https://cdn.discordapp.com/attachments/907377744717955082/1060192921401438258/image.png">La qualité depuis 70ans</a></p>
        <h1 id="jardi_t"><a href="https://cdn.discordapp.com/attachments/907377744717955082/1060192921401438258/image.png">Tout le jardin</a></h1>
    </article>
    <nav class="navbar navbar-expand-xxl navbar-light bg-success">
        <a class="navbar-brand" href="#">JARDITOU</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="index.phtml">Accueil</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="tableau.phtml">Nos Produits</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="contact.phtml">Contact</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="a_propos.phtml">A propos</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="compte.phtml">Mon Compte</a>
                </li>
            </ul>
            <form class="d-flex">
            <input class="form-control me-2" type="search" placeholder="Votre promotion" aria-label="Votre promotion">
                <button class="btn btn-outline-light" type="submit">Rechercher</button>
            </form>
    </nav>

    <section id="promo_img">
        <img src="./src/img/promotion.jpg" alt="promotion""">
    </section>
   </header>
   <section id="error">
   <h1>Erreur 404</h1>
    <img id="err" src="./src/img/error_404.jpg" alt="erreur" title="Erreur">
   </section>
    

   <footer class="bg-dark">
    <ul>
    <li class="nav-item"><a class="nav-link active" href="mention-legales">Mentions légales</a></li>
    <li class="nav-item"><a class="nav-link active" href="horaires.phtml">Horaires</a></li>
    <li class="nav-item"><a class="nav-link active" href="sitemap.phtml">Plan du site</a></li>
       </ul>
    </footer>
    
</body>
</html>