<!DOCTYPE html>
<html lang="fr">
    <!-- debut de la balise head-->
<head>
 <!--debut de la balise meta --> 
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
<!--Fin de la balise meta-->

<!--Titre et CSS-->
    <title>Liste des produits</title>
    <link rel="stylesheet" href="./jarditou_css/assets/css/styles.css">
     <!-- Bootstrap-->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
</head>
<!--Fin de la balise head-->

<!--debut de la balise body -->
<body>
<header>
        <img id="logoj" src="./src/img/jarditou_logo.png" alt="jarditou logo">
        <article>
         <p class="text-center"><a href="https://cdn.discordapp.com/attachments/907377744717955082/1060192921401438258/image.png">La qualité depuis 70ans</a></p>
        <h1 id="jardi_t"><a href="https://cdn.discordapp.com/attachments/907377744717955082/1060192921401438258/image.png">Tout le jardin</a></h1>
    </article>
    <nav class="navbar navbar-expand-xxl navbar-light bg-success">
        <a class="navbar-brand" href="#">JARDITOU</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="index.phtml">Accueil</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="tableau.phtml">Nos Produits</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="contact.phtml">Contact</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="a_propos.phtml">A propos</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="compte.phtml">Mon Compte</a>
                </li>
            </ul>
            <form class="d-flex">
            <input class="form-control me-2" type="search" placeholder="Votre promotion" aria-label="Votre promotion">
                <button class="btn btn-outline-light" type="submit">Rechercher</button>
            </form>
    </nav>
    <section id="promo_img">
        <img src="./src/img/promotion.jpg" alt="promotion">
    </section>
    </header>   
        <h1>Tableau</h1>
        <hr>
    <table>
        <thead>
            <tr>
                <th>Photo</th>
                <th>ID</th>
                <th>Catégorie</th>
                <th>Libellé</th>
                <th>Prix</th>
                <th>Couleur</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td><img id="photo_1" src="./src/img/7.png" alt="premier produit de jarditou" title="photo1"></td>
                <td>7</td>
                <td>Barbecues</td>
                <td>Aramis</td>
                <td>110.00€</td>
                <td>Brun</td>
            </tr>
            <tr>
                <td> <img id="photo_2" src="./src/img/8.png" border="0" alt="deuxieme produit de jarditou" title="photo2"> </td>
                <td>8</td>
                <td>Barbecues</td>
                <td>Athos</td>
                <td>249.99€</td>
                <td>Noir</td>
            </tr>
            <tr>
                <td><img id="photo_3" src="./src/img/11.png" border="0" alt="troisieme produit de jarditou" title="photo3"></td>
                <td>11</td>
                <td>Barbecues</td>
                <td>Clatronic</td>
                <td>135.90€</td>
                <td>Chrome</td>
            </tr>
            <tr>
                <td><img id="photo_4" src="./src/img/12.png" border="0" alt="quatrieme produit de jarditou" title="photo4"></td>
                <td>12</td>
                <td>Barbecues</td>
                <td>Camping</td>
                <td>88.00€</td>
                <td>Noir</td>
            </tr>
            <tr>
                <td><img id="photo_5" src="./src/img/13.png" alt="cinquieme produit de jarditou" title="photo5"></td>
                <td>13</td>
                <td>Brouette</td>
                <td>Green</td>
                <td>49.00€</td>
                <td>Verte</td>
            </tr>
        </tbody>
    </table>
    <hr>
    
    <footer class="bg-dark">
    <ul>
    <li class="nav-item"><a class="nav-link active" href="mention-legales">Mentions légales</a></li>
    <li class="nav-item"><a class="nav-link active" href="horaires.phtml">Horaires</a></li>
    <li class="nav-item"><a class="nav-link active" href="sitemap.phtml">Plan du site</a></li>
       </ul>
    </footer>

</body>
</html>